#include "territorios.h"

;; PARA ME LEMBRAR
;; FAZER FUNCAO GERARNOVOTERRENO(COORDENADA X, COORDENADA Y)
;; ONDE O JOGADOR ESTA NA POSICAO - 500, 000 (EXEMPLO)O TERRENO É GERADO NA DIREÇAO QUE O JOGADOR VAI, POR EXEMPLO
;; ESQUERDA OESTE GERARNOVOTERRENO(PLAYERX - 500, PLAYERY)
;; DIREITA ESTE GERARNOVOTERRENO(PLAYERX + 500, PLAYERY)
;; CIMA NORTE GERARNOVOTERRENO(PLAYERX, PLAYERY + 500)
;; BAIXO SUL GERARNOVOTERRENO(PLAYERX, PLAYERY - 500)